# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx
r:
  - 3.6.3
  - 4.0.0
  - 4.0.1
  - 4.0.2
  - devel
after_success:
    - Rscript -e 'covr::codecov(type = "all")'
